name: the-hub

services:
  api:
    build:
      context: ./services/backend
      target: prod
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      target: prod
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://api:8080
    depends_on:
      - api
