name: build-backend
on:
  push:
    branches: [ main ]
    paths:
      - "services/spring/**"
      - ".github/workflows/build-backend.yml"

jobs:
  docker:
    name: Build & Push multi-arch (amd64, arm64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # needed for GHCR
    defaults:
      run:
        working-directory: services/spring
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: services/spring
          file: services/spring/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/the-hub-api:latest
            ghcr.io/${{ github.repository_owner }}/the-hub-api:${{ github.sha }}