name: Apply Supabase migrations

on:
  push:
    branches:
      - main

jobs:
  migrate-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Link PROD and push migrations
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF_PROD }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF
          supabase db push
