# .github/workflows/prettier.yml
name: Prettier (web)

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node + pnpm cache based on the ROOT lockfile
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Make pnpm available
      - run: corepack enable

      # Install ALL workspace deps from the root (uses pnpm-lock.yaml at root)
      - run: pnpm install --frozen-lockfile

      # Run the prettier check in apps/web (uses web's devDeps + config)
      - run: pnpm -C apps/web run format:check
