name: Prettier (web)

on:
  pull_request:
    branches: [dev, main]

jobs:
  prettier:
    name: prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable corepack BEFORE setting up Node
      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # Prepare pnpm version after Node setup
      - run: corepack prepare pnpm@10.14.0 --activate

      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web run format:check