name: Prettier (web)

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # ↓ Enable corepack and explicitly activate a pnpm version
      - run: corepack enable
      - run: corepack prepare pnpm@10.14.0 --activate

      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web run format:check
