name: Web CI

on:
  pull_request:
    branches: [dev, main]

concurrency:
  group: web-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect:
    name: detect changes
    runs-on: ubuntu-latest
    outputs:
      web_changed: ${{ steps.changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - id: changed
        uses: tj-actions/changed-files@v46
        with:
          files: |
            apps/web/**
            packages/**
            pnpm-lock.yaml
            package.json
            pnpm-workspace.yaml
            .github/workflows/web-ci.yml

  prettier:
    name: prettier
    needs: detect
    if: needs.detect.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack prepare pnpm@10.14.0 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C apps/web run format:check

  test:
    name: test (web)
    needs: detect
    if: needs.detect.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack prepare pnpm@10.14.0 --activate
      - run: pnpm install --frozen-lockfile
      - name: Run unit tests
        working-directory: apps/web
        env:
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
          # keep vitest API server off for security (and because we don't need UI)
          VITEST_API: "0"
        run: pnpm test:run -- --reporter=dot

  build:
    name: build (web)
    needs: [detect, test] # only build if tests passed
    if: needs.detect.outputs.web_changed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: corepack prepare pnpm@10.14.0 --activate
      - run: pnpm -C apps/web install --frozen-lockfile
      - name: Build
        working-directory: apps/web
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SITE_URL: "http://localhost:3000"
          NEXT_TELEMETRY_DISABLED: "1"
        run: pnpm build

  noop:
    # If web didn't change, post a single success so PRs still get green checks
    name: no web changes (noop)
    needs: detect
    if: needs.detect.outputs.web_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in apps/web — skipping prettier, tests, and build."